## This configuration.yaml file is provided by the Home Assistant Core iocage-jail for TrueNAS Core
# Learn more at https://www.home-assistant.io/docs/configuration

homeassistant:
  # https://www.home-assistant.io/docs/configuration/customizing-devices/
  customize: !include customize.yaml
  # https://www.home-assistant.io/docs/configuration/packages/#create-a-packages-folder
  packages: !include_dir_named packages

http:
  # https://www.home-assistant.io/integrations/http/#ip_ban_enabled
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxy_hosts

## Configure a default setup of Home Assistant Core (frontend, api, etc)
# Learn more at https://www.home-assistant.io/integrations/default_config
default_config:

logger:
  default: warning
  logs:
    custom_components.ocpp: warning
    custom_components.pyscript.file: info

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js

google_assistant: !include google_assistant.yaml

# Text to speech
tts:
  - platform: google_translate

sonos:
  media_player:
    hosts:
      - 10.10.10.90
      - 10.10.10.91
    #hosts: !secret network_sonos_hosts
    advertise_addr: !secret network_hass_host_sonos

powercalc:
  force_update_frequency: 00:20:00
  create_energy_sensors: true
  enable_autodiscovery: false
  power_sensor_naming: "{} Power"
  energy_sensor_naming: "{} Energy"

recorder:
  purge_keep_days: 14
  commit_interval: 10
  exclude:
    entity_globs:
      - sensor.solaredge_*
  include:
    entities:
      - sensor.solaredge_current_power
      - sensor.solaredge_energy_this_month
      - sensor.solaredge_energy_this_year
      - sensor.solaredge_energy_today
      - sensor.solaredge_lifetime_energy
      - sensor.solaredge_ac_power
      - sensor.solaredge_ac_pf
      - sensor.solaredge_ac_energy_kwh
      - sensor.solaredge_ac_current
      - sensor.solaredge_temp_sink
      - sensor.solaredge_ac_frequency
      - sensor.solaredge_ac_va

history:
  exclude:
    domains:
      - weather
      - automation
      - media_player
    entities:
      - binary_sensor.updater
    entity_globs:
      - script.*
      - input_*
      - switch.schedule_*
      - switch.adaptive_lighting*
      - automation
      - adguard

rest_command:
  preheat_car:
    url: "https://car.eliens.co/preconditioning/VXKUKZKXZNW066336/1"

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include binary_sensors.yaml
light: !include lights.yaml
sensor: !include sensors.yaml
sensor powercalc: !include powercalc_sensors.yaml
notify: !include notify.yaml
utility_meter: !include utility_meter.yaml
input_number: !include input_numbers.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
template: !include templates.yaml
climate: !include climate.yaml
pyscript: !include pyscript/config.yaml
alarm_control_panel: !include alarms.yaml