## This configuration.yaml file is provided by the Home Assistant Core iocage-jail for TrueNAS Core
# Learn more at https://www.home-assistant.io/docs/configuration

homeassistant:
  # https://www.home-assistant.io/docs/configuration/customizing-devices/
  customize: !include customize.yaml
  # https://www.home-assistant.io/docs/configuration/packages/#create-a-packages-folder
  packages: !include_dir_named packages

http:
  # https://www.home-assistant.io/integrations/http/#ip_ban_enabled
  ip_ban_enabled: True
  login_attempts_threshold: 5

## Configure a default setup of Home Assistant Core (frontend, api, etc)
# Learn more at https://www.home-assistant.io/integrations/default_config
default_config:

# Text to speech
tts:
  - platform: google_translate

recorder:
  commit_interval: 10
  exclude:
    entity_globs:
      - sensor.pi_*
      - switch.pi_*
      - sensor.solaredge_*
  include:
    entities:
      - sensor.solaredge_current_power
      - sensor.solaredge_energy_this_month
      - sensor.solaredge_energy_this_year
      - sensor.solaredge_energy_today
      - sensor.solaredge_lifetime_energy

history:
  exclude:
    domains:
      - weather
      - automation
      - media_player
    entities:
      - binary_sensor.updater
      - sensor.blood_sugar
    entity_globs:
      - sensor.pi_*
      - switch.pi_*
      - script.*
      - input_*
      - automation

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include binary_sensors.yaml
light: !include lights.yaml
sensor: !include sensors.yaml
notify: !include notify.yaml
utility_meter: !include utility_meter.yaml
input_number: !include input_numbers.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
