- platform: integration
  unit_prefix: 'k'
  source: sensor.bedroom_ceiling_1_power
  name: 'bedroom_ceiling_1_energy'
- platform: integration
  unit_prefix: 'k'
  source: sensor.bedroom_ceiling_2_power
  name: 'bedroom_ceiling_2_energy'
- platform: integration
  unit_prefix: 'k'
  source: sensor.office_ceiling_power
  name: 'office_ceiling_energy'
- platform: integration
  unit_prefix: 'k'
  source: sensor.living_room_corner_power
  name: 'living_room_corner_energy'
- platform: integration
  unit_prefix: 'k'
  source: sensor.living_room_ceiling_power
  name: 'living_room_ceiling_energy'
- platform: integration
  unit_prefix: 'k'
  source: sensor.dining_table_up_power
  name: 'dining_table_up_energy'
- platform: integration
  unit_prefix: 'k'
  source: sensor.dining_table_down_power
  name: 'dining_table_down_energy'
- platform: integration
  unit_prefix: 'k'
  source: sensor.kitchen_ceiling_power
  name: 'kitchen_ceiling_energy'
- platform: integration
  unit_prefix: 'k'
  source: sensor.kitchen_cabinets_power
  name: 'kitchen_cabinets_energy'
- platform: integration
  unit_prefix: 'k'
  source: sensor.side_kitchen_window_power
  name: 'side_kitchen_window_energy'
- platform: integration
  unit_prefix: 'k'
  source: sensor.side_kitchen_ceiling_1_power
  name: 'side_kitchen_ceiling_1_energy'
- platform: integration
  unit_prefix: 'k'
  source: sensor.side_kitchen_ceiling_2_power
  name: 'side_kitchen_ceiling_2_energy'
- platform: integration
  unit_prefix: 'k'
  source: sensor.side_kitchen_cabinets_power
  name: 'side_kitchen_cabinets_energy'
- platform: integration
  source: sensor.powercalc_google_assistant_devices_power
  unit_prefix: k
  name: 'powercalc_google_assistant_devices_energy'
  round: 2
- platform: integration
  source: sensor.powercalc_nas_power
  unit_prefix: k
  name: 'powercalc_nas_energy'
  round: 2
- platform: integration
  source: sensor.powercalc_networking_devices_power
  unit_prefix: k
  name: 'powercalc_networking_devices_energy'
  round: 2
- platform: integration
  source: sensor.living_room_sonos_power
  unit_prefix: k
  name: 'powercalc_living_room_sonos_energy'
  round: 2
