- platform: file
  name: utilitydaily
  filename: /mnt/logs/utility_daily.csv
  timestamp: true
- platform: file
  name: utilitymonthly
  filename: /mnt/logs/utility_monthly.csv
  timestamp: true
- platform: file
  name: utilityhourly
  filename: /mnt/logs/utility_hourly.csv
  timestamp: true
