- platform: template
  sensors:
    power_consumption_total_net:
      friendly_name: 'Power Usage (Net)'
      unit_of_measurement: 'W'
      value_template: "{{ states('sensor.power_consumption_watt')|float + (states('sensor.solaredge_current_power')|float | round(0)) - states('sensor.power_production_watt')|float }}"
    power_flow_net:
      friendly_name: 'Power Flow'
      unit_of_measurement: 'W'
      value_template: "{{ states('sensor.power_consumption_watt')|float - states('sensor.power_production_watt')|float }}"
    energy_production_daily_total_watt:
      friendly_name: 'Energy Production'
      unit_of_measurement: "Wh"
      value_template: "{{ (states('sensor.energy_production_daily_total_meter') | float) * 1000 | round(0) }}"
    solar_energy_daily_watthour:
      friendly_name: 'Solar Energy Today'
      unit_of_measurement: 'kWh'
      value_template: "{{ (states('sensor.solaredge_energy_today') | float) / 1000 | round(3) }}"
- platform: average
  unique_id: average_consumption_net
  name: Average power consumption (net)
  entities: 
    - sensor.power_consumption_total_net
  duration:
    minutes: 5
  process_undef_as: 0
- platform: average
  unique_id: living_room_illuminance
  name: Living Room Illuminance
  entities:
    - sensor.motion_a_illuminance
    - sensor.motion_b_illuminance
- platform: average
  unique_id: average_consumption
  name: Average Power Consumption
  entities:
    - sensor.power_consumption_watt
  duration:
    minutes: 5
  process_undef_as: 0
- platform: average
  unique_id: average_production
  name: Average Power Production
  entities:
    - sensor.power_production_watt
  duration:
    minutes: 5
  process_undef_as: 0
- platform: average
  unique_id: average_power_plug_1
  name: Average Power Shelly Plug 1
  entities:
    - sensor.shelly_plug_1_power
  duration:
    minutes: 5
  process_undef_as: 0
- platform: average
  unique_id: average_power_plug_2
  name: Average Power Shelly Plug 2
  entities:
    - sensor.shelly_plug_2_power
  duration:
    minutes: 5
  process_undef_as: 0
