- platform: dsmr
  port: /dev/cuaU0
  dsmr_version: 5
- platform: template
  sensors:
    energy_consumption_total_custom:
      friendly_name: 'Energy Consumption (Total)'
      unit_of_measurement: 'kWh'
      value_template: "{{ (states('sensor.energy_consumption_tarif_1')|float + states('sensor.energy_consumption_tarif_2')|float) | round(3) }}"
    energy_production_total_custom:
      friendly_name: 'Energy Production (Total)'
      unit_of_measurement: 'kWh'
      value_template: "{{ (states('sensor.energy_production_tarif_1')|float + states('sensor.energy_production_tarif_2')|float) | round(3) }}"
    power_consumption_total_net:
      friendly_name: 'Power Usage (Net)'
      unit_of_measurement: 'W'
      value_template: "{{ states('sensor.power_consumption_watt')|float + (states('sensor.solaredge_current_power')|float | round(0)) - states('sensor.power_production_watt')|float }}"
    power_consumption_watt:
      friendly_name: 'Power Consumption'
      unit_of_measurement: 'W'
      value_template: "{{ (states('sensor.power_consumption')|float) * 1000 }}"
    power_production_watt:
      friendly_name: 'Power Production'
      unit_of_measurement: 'W'
      value_template: "{{ (states('sensor.power_production')|float) * 1000 }}"
    power_flow_net:
      friendly_name: 'Power Flow'
      unit_of_measurement: 'W'
      value_template: "{{ states('sensor.power_consumption_watt')|float - states('sensor.power_production_watt')|float }}"
    energy_production_daily_total_watt:
      friendly_name: 'Energy Production'
      unit_of_measurement: "Wh"
      value_template: "{{ (states('sensor.energy_production_daily_total_meter') | float) * 1000 | round(0) }}"
    energy_consumption_daily_total_watt:
      friendly_name: 'Energy Consumption'
      unit_of_measurement: "Wh"
      value_template: "{{ (states('sensor.energy_daily_total_meter') | float) * 1000 | round(0) }}"
    solar_energy_daily_watthour:
      friendly_name: 'Solar Energy Today'
      unit_of_measurement: 'kWh'
      value_template: "{{ (states('sensor.solaredge_energy_today') | float) / 1000 | round(3) }}"
- platform: statistics
  name: average_consumption
  entity_id: sensor.power_consumption_watt
  precision: 0
  max_age:
    minutes: 2
- platform: statistics
  name: average_production
  entity_id: sensor.power_production_watt
  precision: 0
  max_age:
    minutes: 2
- platform: statistics
  name: average_consumption_net
  entity_id: sensor.power_consumption_total_net
  precision: 0
  max_age:
    minutes: 2
- platform: statistics
  name: average_gas
  entity_id: sensor.hourly_gas_consumption
  precision: 3
  max_age:
    minutes: 30
