- platform: template
  sensors:
    power_consumption_total_net:
      friendly_name: 'Power Usage (Net)'
      unit_of_measurement: 'W'
      value_template: "{{ states('sensor.power_consumption_watt')|float(0) + (states('sensor.solaredge_ac_power')|float(0) | round(0)) - states('sensor.power_production_watt')|float(0) }}"
    power_flow_net:
      friendly_name: 'Power Flow'
      unit_of_measurement: 'W'
      value_template: "{{ states('sensor.power_consumption_watt')|float(0) - states('sensor.power_production_watt')|float(0) }}"
    energy_production_daily_total_watt:
      friendly_name: 'Energy Production'
      unit_of_measurement: "Wh"
      value_template: "{{ (states('sensor.energy_production_daily_total_meter') | float(0)) * 1000 | round(0) }}"
    solar_energy_daily_watthour:
      friendly_name: 'Solar Energy Today'
      unit_of_measurement: 'kWh'
      value_template: "{{ (states('sensor.solaredge_energy_today') | float(0)) / 1000 | round(3) }}"
    power_production_tariff:
      friendly_name: 'Power Production Tariff'
      unit_of_measurement: '€/kWh'
      value_template: "{{ ((states('sensor.current_electricity_market_price') | float(0.1)) - ((states('sensor.current_electricity_sourcing_markup') | float(0.023)) - 0.029)) * 1.21 }}"
- platform: average
  unique_id: average_consumption_net
  name: Average power consumption (net)
  entities: 
    - sensor.power_consumption_total_net
  duration:
    minutes: 5
  process_undef_as: 0
- platform: average
  unique_id: living_room_illuminance
  name: Living Room Illuminance
  process_undef_as: 0
  entities:
    - sensor.motion_a_illuminance
    - sensor.motion_b_illuminance
  duration:
    minutes: 5
- platform: average
  unique_id: average_consumption
  name: Average Power Consumption
  entities:
    - sensor.power_consumption_watt
  duration:
    minutes: 5
  process_undef_as: 0
- platform: average
  unique_id: average_production
  name: Average Power Production
  entities:
    - sensor.power_production_watt
  duration:
    minutes: 5
  process_undef_as: 0
- platform: average
  unique_id: average_power_plug_1
  name: Average Power Shelly Plug 1
  entities:
    - sensor.shelly_plug_1_power
  duration:
    minutes: 30
  process_undef_as: 0
- platform: average
  unique_id: average_power_plug_2
  name: Average Power Shelly Plug 2
  entities:
    - sensor.shelly_plug_2_power
  duration:
    minutes: 20
  process_undef_as: 0
- platform: statistics
  name: "Average Electricity Cost"
  unique_id: average_electricity_cost
  entity_id: sensor.zonneplan_current_electricity_tariff
  state_characteristic: mean
  sampling_size: 20
  max_age:
    hours: 24
- platform: statistics
  name: "Average Gas Cost"
  unique_id: average_gas_cost
  entity_id: sensor.zonneplan_current_gas_tariff
  state_characteristic: mean
  sampling_size: 20
  max_age:
    hours: 24
- platform: average
  unique_id: average_power_shelly_pm_airco
  name: Average Power Airco
  entities:
    - sensor.shelly1pm_airco_power
  duration:
    minutes: 30
  process_undef_as: 0
- platform: average
  unique_id: average_power_flow
  name: Average Power Flow
  entities:
    - sensor.power_flow_net
  duration:
    minutes: 10
