- platform: circadian_lighting
  name: Circadian Lighting Office
  min_brightness: 60
  lights_ct:
    - light.office_ceiling
- platform: circadian_lighting
  name: Circadian Lighting Bedroom
  disable_entity: input_boolean.woken_up
  disable_state: 'off'
  lights_ct:
    - light.bedroom_ceiling_1
    - light.bedroom_ceiling_2
- platform: circadian_lighting
  name: Downstairs ceiling
  min_brightness: 40
  disable_entity: input_boolean.enable_circadian_downstairs
  disable_state: 'off'
  lights_ct:
    - light.living_room_ceiling
    - light.dining_table_up
    - light.kitchen_ceiling
- platform: circadian_lighting
  name: Downstairs other
  min_brightness: 60
  disable_entity: input_boolean.enable_circadian_downstairs
  disable_state: 'off'
  lights_ct:
    - light.living_room_corner
  lights_brightness:
    - light.kitchen_cabinets
