blueprint:
  name: Motion-activated Light based with illuminance and sleep
  description: Turn on a light when motion is detected and the illuminance is below a given amount. Also supports sleep mode.
  domain: automation
  source_url: https://github.com/cascer1/ha-config/blob/master/blueprints/automation/cascer1/motion_light_illuminance_sleep.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    sleep_light_target:
      name: Sleep Lights
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          step: 15
          max: 3600
          unit_of_measurement: seconds
    light_sensor:
      name: Light Level Sensor
      selector:
        entity:
          device_class: illuminance
    light_level:
      name: Light Level
      description: Light level below which to turn on the lights.
      selector:
        number:
          min: 0
          max: 500
          step: 10
          unit_of_measurement: lx
    automatic_control_boolean:
      name: Automatic control boolean
      description: This toggle enables or disables automatic lights.
      selector:
        entity:
          domain: input_boolean
    sleep_mode_switch:
      name: Sleep Mode Switch
      description: Switch that tracks sleep mode
      selector:
        entity:
          domain: switch

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

condition:
  - condition: state
    entity_id: !input automatic_control_boolean
    state: 'on'

action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: !input light_sensor
        below: !input light_level
      - condition: state
        entity_id: !input sleep_mode_switch
        state: 'on'
      sequence:
        - service: light.turn_on
          target: !input sleep_light_target
    - conditions:
      - condition: numeric_state
        entity_id: !input light_sensor
        below: !input light_level
      - condition: state
        entity_id: !input sleep_mode_switch
        state: 'off'
      sequence:
        - service: light.turn_on
          target: !input light_target
  - wait_for_trigger:
    - platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - delay: !input no_motion_wait
  - condition: state
    entity_id: !input automatic_control_boolean
    state: 'on'
  - service: light.turn_off
    target: !input light_target
