blueprint:
  source_url: https://github.com/cascer1/ha-config/blob/master/blueprints/automation/cascer1/reset_automatic_control.yaml
  name: "Reset automatic control"
  description: Reset automatic control booleans after inactivity in a room.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
    automatic_control_boolean:
      name: Automatic control boolean
      description: Input boolean to keep track of automatic control for the lights
      selector:
        entity:
          domain: input_boolean

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: 'off'
    for: '03:00:00'

action:
  - service: input_boolean.turn_on
    target:
      entity_id: !input automatic_control_boolean
